.PHONY: install
install:
	poetry install
.PHONY: server
server:
	poetry run python -m core.manage runserver
.PHONY: makemigrations
makemigrations:
	poetry run python -m core.manage makemigrations
.PHONY: migrate
migrate:
	poetry run python -m core.manage migrate
.PHONY: superuser
superuser:
	poetry run python -m core.manage createsuperuser
.PHONY: update
update:	install migrate ;
